SELECT 
	kcu.CONSTRAINT_NAME AS [Name],
	kcu.COLUMN_NAME AS [ColumnName], 
	tc.CONSTRAINT_TYPE AS [TypeName]
FROM 
	INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS tc
INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS kcu ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
WHERE 
	tc.TABLE_SCHEMA = @Schema AND tc.TABLE_NAME = @TableName
