SELECT
	SPECIFIC_SCHEMA AS [Schema],
	SPECIFIC_NAME AS [Name]
FROM
	INFORMATION_SCHEMA.ROUTINES
WHERE
	NOT 
	(
		ROUTINE_SCHEMA = 'dbo'
		AND ROUTINE_NAME LIKE 'dt[_]%'
		AND SUBSTRING(CAST(SERVERPROPERTY('productversion') AS varchar(20)), 1, 1) = 8
	) 
	AND (DATA_TYPE != 'TABLE' OR DATA_TYPE IS NULL)
	AND ROUTINE_TYPE = 'PROCEDURE'