SELECT
	SPECIFIC_SCHEMA AS [Schema],
    SPECIFIC_NAME AS [Name],
	CHARACTER_MAXIMUM_LENGTH AS [ReturnMaxLength],
	CAST(NUMERIC_PRECISION AS int) AS [ReturnPrecision],
	CAST(NUMERIC_SCALE AS int) AS [ReturnScale],
	DATA_TYPE AS [ReturnTypeName],
	CAST((CASE WHEN DATA_TYPE = 'TABLE' THEN 1 ELSE 0 END) AS bit) AS [IsTableValued]
FROM
	INFORMATION_SCHEMA.ROUTINES
WHERE
	NOT 
	(
		ROUTINE_SCHEMA = 'dbo'
        AND ROUTINE_NAME LIKE 'dt[_]%'
        AND SUBSTRING(CAST(SERVERPROPERTY('productversion') AS varchar(20)), 1, 1) = 8
	)
    AND ROUTINE_TYPE = 'FUNCTION'